<a href="https://colab.research.google.com/github/youssefbourais0310/Neural_Networks/blob/main/csv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/my.csv")
df

      448babed-2c53-47e6-965c-388e34c9073e.jpg 08278_Plantae_Tracheophyta_Magnoliopsida_Gentianales_Apocynaceae_Nerium_oleander
0      f601766d-adb7-4aee-b8e9-c1693667d3f8.jpg 08278...
1      7f87540d-092f-4d1e-933b-10ac5bacbfac.jpg 08278...
2      cad9ae7b-2918-438a-a2fb-bd6abd5eb69f.jpg 08278...
3      9f70c3e7-1370-47c2-aa75-6c7378bccc63.jpg 08278...
4      52ba896b-bbd1-4456-b281-4e6d578c0c12.jpg 08278...
...                                                  ...
22589  960b6c77-c800-43fb-818d-330577bef239.jpg 05802...
22590  97c4cad8-4ed2-446a-9c9b-9ce3656ab6d1.jpg 05802...
22591  c036fd80-99e5-47d6-a805-0a017cbeb199.jpg 05802...
22592  05eee851-dda2-4807-adec-9c32e4d1292f.jpg 05802...
22593  9029c188-93b5-4d85-b39a-e9403d9e5aa0.jpg 05802...

[22594 rows x 1 columns]

In [10]:
df['448babed-2c53-47e6-965c-388e34c9073e.jpg 08278_Plantae_Tracheophyta_Magnoliopsida_Gentianales_Apocynaceae_Nerium_oleander'].str.split(' ', expand=True)

0        [f601766d-adb7-4aee-b8e9-c1693667d3f8.jpg, 082...
1        [7f87540d-092f-4d1e-933b-10ac5bacbfac.jpg, 082...
2        [cad9ae7b-2918-438a-a2fb-bd6abd5eb69f.jpg, 082...
3        [9f70c3e7-1370-47c2-aa75-6c7378bccc63.jpg, 082...
4        [52ba896b-bbd1-4456-b281-4e6d578c0c12.jpg, 082...
                               ...
22589    [960b6c77-c800-43fb-818d-330577bef239.jpg, 058...
22590    [97c4cad8-4ed2-446a-9c9b-9ce3656ab6d1.jpg, 058...
22591    [c036fd80-99e5-47d6-a805-0a017cbeb199.jpg, 058...
22592    [05eee851-dda2-4807-adec-9c32e4d1292f.jpg, 058...
22593    [9029c188-93b5-4d85-b39a-e9403d9e5aa0.jpg, 058...
Name: 448babed-2c53-47e6-965c-388e34c9073e.jpg 08278_Plantae_Tracheophyta_Magnoliopsida_Gentianales_Apocynaceae_Nerium_oleander, Length: 22594, dtype: object

In [19]:
df1 = df['448babed-2c53-47e6-965c-388e34c9073e.jpg 08278_Plantae_Tracheophyta_Magnoliopsida_Gentianales_Apocynaceae_Nerium_oleander'].str.split(' ', expand=True)

In [20]:
df1

,0,1
0,f601766d-adb7-4aee-b8e9-c1693667d3f8.jpg,08278_Plantae_Tracheophyta_Magnoliopsida_Genti...
1,7f87540d-092f-4d1e-933b-10ac5bacbfac.jpg,08278_Plantae_Tracheophyta_Magnoliopsida_Genti...
2,cad9ae7b-2918-438a-a2fb-bd6abd5eb69f.jpg,08278_Plantae_Tracheophyta_Magnoliopsida_Genti...
3,9f70c3e7-1370-47c2-aa75-6c7378bccc63.jpg,08278_Plantae_Tracheophyta_Magnoliopsida_Genti...
4,52ba896b-bbd1-4456-b281-4e6d578c0c12.jpg,08278_Plantae_Tracheophyta_Magnoliopsida_Genti...
...,...,...
22589,960b6c77-c800-43fb-818d-330577bef239.jpg,05802_Plantae_Tracheophyta_Liliopsida_Alismata...
22590,97c4cad8-4ed2-446a-9c9b-9ce3656ab6d1.jpg,05802_Plantae_Tracheophyta_Liliopsida_Alismata...
22591,c036fd80-99e5-47d6-a805-0a017cbeb199.jpg,05802_Plantae_Tracheophyta_Liliopsida_Alismata...
22592,05eee851-dda2-4807-adec-9c32e4d1292f.jpg,05802_Plantae_Tracheophyta_Liliopsida_Alismata...
22593,9029c188-93b5-4d85-b39a-e9403d9e5aa0.jpg,05802_Plantae_Tracheophyta_Liliopsida_Alismata...

In [23]:
df2 = df1.rename(columns={"0": "id", "1": "breed"})
df2

,0,1
0,f601766d-adb7-4aee-b8e9-c1693667d3f8.jpg,08278_Plantae_Tracheophyta_Magnoliopsida_Genti...
1,7f87540d-092f-4d1e-933b-10ac5bacbfac.jpg,08278_Plantae_Tracheophyta_Magnoliopsida_Genti...
2,cad9ae7b-2918-438a-a2fb-bd6abd5eb69f.jpg,08278_Plantae_Tracheophyta_Magnoliopsida_Genti...
3,9f70c3e7-1370-47c2-aa75-6c7378bccc63.jpg,08278_Plantae_Tracheophyta_Magnoliopsida_Genti...
4,52ba896b-bbd1-4456-b281-4e6d578c0c12.jpg,08278_Plantae_Tracheophyta_Magnoliopsida_Genti...
...,...,...
22589,960b6c77-c800-43fb-818d-330577bef239.jpg,05802_Plantae_Tracheophyta_Liliopsida_Alismata...
22590,97c4cad8-4ed2-446a-9c9b-9ce3656ab6d1.jpg,05802_Plantae_Tracheophyta_Liliopsida_Alismata...
22591,c036fd80-99e5-47d6-a805-0a017cbeb199.jpg,05802_Plantae_Tracheophyta_Liliopsida_Alismata...
22592,05eee851-dda2-4807-adec-9c32e4d1292f.jpg,05802_Plantae_Tracheophyta_Liliopsida_Alismata...
22593,9029c188-93b5-4d85-b39a-e9403d9e5aa0.jpg,05802_Plantae_Tracheophyta_Liliopsida_Alismata...

In [24]:
df2.to_csv('BRS.csv')