<a href="https://colab.research.google.com/github/youssefbourais0310/Neural_Networks/blob/main/csv2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/labelss.csv")

In [6]:
df

,id,breed
0,f601766d-adb7-4aee-b8e9-c1693667d3f8.jpg,08278_Plantae_Tracheophyta_Magnoliopsida_Genti...
1,7f87540d-092f-4d1e-933b-10ac5bacbfac.jpg,08278_Plantae_Tracheophyta_Magnoliopsida_Genti...
2,cad9ae7b-2918-438a-a2fb-bd6abd5eb69f.jpg,08278_Plantae_Tracheophyta_Magnoliopsida_Genti...
3,9f70c3e7-1370-47c2-aa75-6c7378bccc63.jpg,08278_Plantae_Tracheophyta_Magnoliopsida_Genti...
4,52ba896b-bbd1-4456-b281-4e6d578c0c12.jpg,08278_Plantae_Tracheophyta_Magnoliopsida_Genti...
...,...,...
22589,960b6c77-c800-43fb-818d-330577bef239.jpg,05802_Plantae_Tracheophyta_Liliopsida_Alismata...
22590,97c4cad8-4ed2-446a-9c9b-9ce3656ab6d1.jpg,05802_Plantae_Tracheophyta_Liliopsida_Alismata...
22591,c036fd80-99e5-47d6-a805-0a017cbeb199.jpg,05802_Plantae_Tracheophyta_Liliopsida_Alismata...
22592,05eee851-dda2-4807-adec-9c32e4d1292f.jpg,05802_Plantae_Tracheophyta_Liliopsida_Alismata...
22593,9029c188-93b5-4d85-b39a-e9403d9e5aa0.jpg,05802_Plantae_Tracheophyta_Liliopsida_Alismata...

In [7]:
df['id'] = df['id'].str.replace('.jpg','')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  """Entry point for launching an IPython kernel.

In [8]:
df

,id,breed
0,f601766d-adb7-4aee-b8e9-c1693667d3f8,08278_Plantae_Tracheophyta_Magnoliopsida_Genti...
1,7f87540d-092f-4d1e-933b-10ac5bacbfac,08278_Plantae_Tracheophyta_Magnoliopsida_Genti...
2,cad9ae7b-2918-438a-a2fb-bd6abd5eb69f,08278_Plantae_Tracheophyta_Magnoliopsida_Genti...
3,9f70c3e7-1370-47c2-aa75-6c7378bccc63,08278_Plantae_Tracheophyta_Magnoliopsida_Genti...
4,52ba896b-bbd1-4456-b281-4e6d578c0c12,08278_Plantae_Tracheophyta_Magnoliopsida_Genti...
...,...,...
22589,960b6c77-c800-43fb-818d-330577bef239,05802_Plantae_Tracheophyta_Liliopsida_Alismata...
22590,97c4cad8-4ed2-446a-9c9b-9ce3656ab6d1,05802_Plantae_Tracheophyta_Liliopsida_Alismata...
22591,c036fd80-99e5-47d6-a805-0a017cbeb199,05802_Plantae_Tracheophyta_Liliopsida_Alismata...
22592,05eee851-dda2-4807-adec-9c32e4d1292f,05802_Plantae_Tracheophyta_Liliopsida_Alismata...
22593,9029c188-93b5-4d85-b39a-e9403d9e5aa0,05802_Plantae_Tracheophyta_Liliopsida_Alismata...

In [15]:
df["breed"] = df["breed"].str[6:]

In [16]:
df

,id,breed
0,f601766d-adb7-4aee-b8e9-c1693667d3f8,Plantae_Tracheophyta_Magnoliopsida_Gentianales...
1,7f87540d-092f-4d1e-933b-10ac5bacbfac,Plantae_Tracheophyta_Magnoliopsida_Gentianales...
2,cad9ae7b-2918-438a-a2fb-bd6abd5eb69f,Plantae_Tracheophyta_Magnoliopsida_Gentianales...
3,9f70c3e7-1370-47c2-aa75-6c7378bccc63,Plantae_Tracheophyta_Magnoliopsida_Gentianales...
4,52ba896b-bbd1-4456-b281-4e6d578c0c12,Plantae_Tracheophyta_Magnoliopsida_Gentianales...
...,...,...
22589,960b6c77-c800-43fb-818d-330577bef239,Plantae_Tracheophyta_Liliopsida_Alismatales_Ar...
22590,97c4cad8-4ed2-446a-9c9b-9ce3656ab6d1,Plantae_Tracheophyta_Liliopsida_Alismatales_Ar...
22591,c036fd80-99e5-47d6-a805-0a017cbeb199,Plantae_Tracheophyta_Liliopsida_Alismatales_Ar...
22592,05eee851-dda2-4807-adec-9c32e4d1292f,Plantae_Tracheophyta_Liliopsida_Alismatales_Ar...
22593,9029c188-93b5-4d85-b39a-e9403d9e5aa0,Plantae_Tracheophyta_Liliopsida_Alismatales_Ar...

In [17]:
df.to_csv(r'/content/drive/MyDrive/csv.csv')